### ISSUE TITLE
possibly wrong order of bands when generating fmask

### ISSUE THREAD

**Issue by Kirill888** [OpenDataCubePipelines/eugl#13]
`Path.rglob()` doesn't guarantee any particular order of output

https://github.com/OpenDataCubePipelines/eugl/blob/2d5f43f2ee31a3a03979bd1b0dfdfccde2ea2fff/eugl/fmask.py#L91-L93

https://github.com/OpenDataCubePipelines/eugl/blob/2d5f43f2ee31a3a03979bd1b0dfdfccde2ea2fff/eugl/fmask.py#L107-L108

It might appear sorted many of the times, but there is no mention in the docs about any kind of sorting order, I suspect this is responsible for bad fmask results currently in datahub s3 bucket.

I would also suggest at least counting number of returned files before proceeding with further computation.

**Comment by sixy6e** [comment]
Fixed via #18
